### ISSUE TITLE
Waiting for new executable release!

### ISSUE THREAD

**Issue by pengfeiZhao1993** [MAC-AutoML/YOCO-BERT#3]

**Comment by skzhang1** [comment]
Thank you very much for your attention. 
Recently, I didn't have time to organize the code because I was busy with other projects. This code can already be run directly. If you have any problems, please send an email to me with your personal contact like wechat, I can help you debug hand in hand.

**Comment by zhengxiawu** [comment]
Thanks for your attention.
We have retested the code and ensure that the code is already executable.
Please install the requirements in https://github.com/MAC-AutoML/YOCO-BERT and follow the steps to run the code!

**Comment by pengfeiZhao1993** [comment]
single GPU or mutiple GPUs ？

**Comment by skzhang1** [comment]
Hi,it only supports single gpu.
